name: Build and Commit Executable

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Haskell Environment
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.8.2'
          stack-version: 'latest'

      - name: Build with Stack
        run: stack install --local-bin-path=./build-output

      - name: Configure Git for Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/steve-anunknown/personal-website.git

      - name: Add Executable to Repository
        run: |
          cp ./build-output/* ./ # Adjust if executable is placed elsewhere
          git add .
          git commit --allow-empty -m "Add built executable"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


